name: HyperClock
version: '1.0.0'
main: org.hyperprojects.hyperclock.HyperClock
api-version: '1.21'
authors: [ Timor ]
description: A simple stopwatch and timer for Minecraft with placeholders from the PlaceholderAPI
website: https://hyrenoss.nl

softdepend: ["PlaceholderAPI"]

commands:
  stopwatch:
    description: Stopwatch command
    usage: /stopwatch <start|stop|reset|status>
  timer:
    description: Timer command
    usage: /timer <start|stop|set|status>

permissions:
  hyperclock.stopwatch.use:
    description: Allows use of HyperClock stopwatch
    default: op
  hyperclock.timer.use:
    description: Allows use of HyperClock timer
    default: op