name: HyperClock
version: '1.0.0'
main: org.hyperprojects.hyperclock.HyperClock
api-version: '1.21'
authors: [ Timor ]
description: HyperClock is a Minecraft plugin with a global stopwatch and/or timer, controllable in-game via commands and permissions, featuring PlaceholderAPI support to display time on scoreboards, tab lists, boss bars, and more!
website: https://hyrenoss.nl

softdepend: ["PlaceholderAPI"]

commands:
  stopwatch:
    description: Stopwatch command
    usage: /stopwatch <start|stop|reset|status>
  timer:
    description: Timer command
    usage: /timer <start|stop|set|status>

permissions:
  hyperclock.stopwatch.use:
    description: Allows use of HyperClock stopwatch
    default: op
  hyperclock.timer.use:
    description: Allows use of HyperClock timer
    default: op